selects = {
    "all_fields": "*",
    "custom_invoice_summary": (
        "opco_nbr AS \"opcoNumber\", "
        "cust_ship_to_nbr AS \"customerNumber\", "
        "trans_dt AS \"invoiceDate\", "
        "invc_due_dt AS \"dueDate\", "
        "invc_ref_nbr_new AS \"invoiceNum\", "
        "orig_trans_tot_amt AS \"origAmount\", "
        "curr_trans_tot_amt AS \"dueAmount\", "
        "trans_cd AS \"transTypeCode\", "
        "sus_modified_on AS \"lastUpdateDT\", "
        "created_by_id AS \"createdBy\", "
        "modified_by_id AS \"modifiedBy\", "
        "seller_id AS \"sellerId\""
    ),
    "delivery_invoice_details": (
        "opco_nbr AS \"opcoNumber\", "
        "cust_ship_to_nbr AS \"customerNumber\", "
        "invc_ref_nbr_new AS \"invoiceNumber\", "
        "trans_cd AS \"transCode\", "
        "trans_dt AS \"transDate\", "
        "dscnt_invc_tot_amt AS \"dscntInvcTotAmt\", "
        "othr_allw_amt AS \"othrAllwAmt\", "
        "dlvr_dt AS \"deliveryDate\", "
        "po_nbr AS \"poNumber\", "
        "mnfst_nbr AS \"mnfstNbr\", "
        "stop_nbr AS \"stopNbr\", "
        "invc_dscnt_dt AS \"invcDscntDate\", "
        "invc_due_dt AS \"invcDueDate\", "
        "dlvr_meth_cd AS \"dlvrMethCd\", "
        "rte_nbr_new AS \"routeNumber\", "
        "rte_to_nbr AS \"routeToNumber\""
    ),
    "invoice_detailed_breakdown": (
        "opco_nbr AS \"opcoNumber\", "
        "cust_ship_to_nbr AS \"customerNumber\", "
        "invc_ref_nbr_new AS \"invoiceNumber\", "
        "trans_cd AS \"transCode\", "
        "trans_dt AS \"transDate\", "
        "dscnt_invc_tot_amt AS \"dscntInvcTotAmt\", "
        "orig_trans_promo_ern_amt AS \"origTransPromoErnAmt\", "
        "orig_trans_sale_tax_amt AS \"origTransSaleTaxAmt\", "
        "orig_trans_misc_tax_amt AS \"origTransMiscTaxAmt\", "
        "orig_trans_subtot_amt AS \"origTransSubtotAmt\", "
        "orig_trans_tot_amt AS \"origTransTotAmt\", "
        "curr_trans_promo_ern_amt AS \"currTransPromoErnAmt\", "
        "curr_trans_sale_tax_amt AS \"currTransSaleTaxAmt\", "
        "curr_trans_misc_tax_amt AS \"currTransMiscTaxAmt\", "
        "curr_trans_subtot_amt AS \"currTransSubTotAmt\", "
        "curr_trans_tot_amt AS \"currTransTotAmt\", "
        "othr_allw_amt AS \"othrAllwAmt\", "
        "ship_addr_id AS \"shippingAddressId\", "
        "dlvr_dt AS \"deliveryDate\", "
        "po_nbr AS \"poNumber\", "
        "src_nbr AS \"sourceNumber\", "
        "orig_case_cnt AS \"originalCaseCount\", "
        "orig_splt_cnt AS \"originalSplitCount\", "
        "curr_case_cnt AS \"currentCaseCount\", "
        "curr_splt_cnt AS \"currentSplitCount\", "
        "posted_to_financials AS \"cleanStatus\""
    ),
    "invoice_full_audit_view": (
        "opco_nbr AS \"opcoNumber\", "
        "cust_ship_to_nbr AS \"customerNumber\", "
        "invc_ref_nbr_new AS \"invoiceNumber\", "
        "trans_cd AS \"transCode\", "
        "trans_dt AS \"transDate\", "
        "dscnt_invc_tot_amt AS \"dscntInvcTotAmt\", "
        "orig_trans_promo_ern_amt AS \"origTransPromoErnAmt\", "
        "orig_trans_sale_tax_amt AS \"origTransSaleTaxAmt\", "
        "orig_trans_misc_tax_amt AS \"origTransMiscTaxAmt\", "
        "orig_trans_subtot_amt AS \"origTransSubtotAmt\", "
        "orig_trans_tot_amt AS \"origTransTotAmt\", "
        "curr_trans_promo_ern_amt AS \"currTransPromoErnAmt\", "
        "curr_trans_sale_tax_amt AS \"currTransSaleTaxAmt\", "
        "curr_trans_misc_tax_amt AS \"currTransMiscTaxAmt\", "
        "curr_trans_subtot_amt AS \"currTransSubTotAmt\", "
        "curr_trans_tot_amt AS \"currTransTotAmt\", "
        "othr_allw_amt AS \"othrAllwAmt\", "
        "ship_addr_id AS \"shippingAddressId\", "
        "dlvr_dt AS \"deliveryDate\", "
        "po_nbr AS \"poNumber\", "
        "src_nbr AS \"sourceNumber\", "
        "orig_case_cnt AS \"originalCaseCount\", "
        "orig_splt_cnt AS \"originalSplitCount\", "
        "curr_case_cnt AS \"currentCaseCount\", "
        "curr_splt_cnt AS \"currentSplitCount\", "
        "posted_to_financials AS \"cleanStatus\""
    )
}
